services:
  jupyter:
    image: jupyter/minimal-notebook
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
      - ..:/home/jovyan/gitRepo
      - ./notebooks:/home/jovyan/notebooks
      - ./configure_environment.sh:/usr/local/bin/before-notebook.d/configure_environment.sh
